#ifndef __MESSAGEBOX_H
#define __MESSAGEBOX_H

#include <linux/ioctl.h> // needed for the _IOW etc stuff used late

#define MESSAGEBOX_IOC_MAGIC  'k'
#define MESSAGEBOX_SET_EXCLUDE_MODE	_IO(MESSAGEBOX_IOC_MAGIC,  0)
#define MESSAGEBOX_SET_INCLUDE_MODE	_IO(MESSAGEBOX_IOC_MAGIC,  1)
#define MESSAGEBOX_DELETE_ALL_MESSAGES_MODE _IOW(MESSAGEBOX_IOC_MAGIC,  2, char*)
#define MESSAGEBOX_MAX_UNREAD_MODE _IOW(MESSAGEBOX_IOC_MAGIC,  3, int)

#define MESSAGEBOX_IOC_MAXNR 1

#endif
